[package]
name = "music-player"
version = "0.1.0"
authors = ["Ryan Blecher <notryanb@gmail.com>"]
edition = "2021"

[dependencies]
cpal = "0.13.4"
eframe = "0.21.3"
id3 = "0.6"
itertools = "0.10"
minimp3 = "0.5.1"
rayon = "1.5"
rfd = "0.6"
rodio = "0.14"
serde = { version = "1", features=["derive"] }
serde_json = "1"
tracing = "0.1.29"
tracing-subscriber = "0.3.3"
walkdir = "2"
rubato = "0.12.0"

[dependencies.confy]
version = "0.4.0"
features = ["yaml_conf"]
default-features = false

[patch.crates-io]
confy = { git = 'https://github.com/rust-cli/confy' }
