name: Rust

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libglib2.0-dev libasound2-dev libpulse-dev
      - name: Install Rust
        run: |
          rustup update stable
          rustup default stable
      - name: Cargo fmt
        run: cargo fmt --all -- --check
      - name: Cargo clippy
        run: cargo clippy --features pulseaudio -- -D warnings
      - name: Cargo build
        run: cargo build --verbose --features pulseaudio
